# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BlaxelAi < Formula
  desc ""
  homepage "https://www.blaxel.ai"
  version "0.1.15"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blaxel-ai/toolkit/releases/download/v0.1.15/blaxel_Darwin_x86_64.tar.gz"
      sha256 "b543f58f3d7a44b4575b401a8c7f375998ba30678965c2b57675e27c69084c92"

      def install
        bin.install "blaxel"
        bin.install_symlink "blaxel" => "bl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blaxel-ai/toolkit/releases/download/v0.1.15/blaxel_Darwin_arm64.tar.gz"
      sha256 "d68d234607b67bfa7608ed94fe079bdafa1f6a2c652db662b1513c1b5d014d00"

      def install
        bin.install "blaxel"
        bin.install_symlink "blaxel" => "bl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/blaxel-ai/toolkit/releases/download/v0.1.15/blaxel_Linux_x86_64.tar.gz"
      sha256 "e76798052b4f9ceaa3dd131e9313373232a9cedfc27eb5a67a692d336ef29b2e"
      def install
        bin.install "blaxel"
        bin.install_symlink "blaxel" => "bl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/blaxel-ai/toolkit/releases/download/v0.1.15/blaxel_Linux_arm64.tar.gz"
      sha256 "92f89d428e76159939cb9ea43beccc422fba8127be2f64765f6c4af2cfae9ea1"
      def install
        bin.install "blaxel"
        bin.install_symlink "blaxel" => "bl"
      end
    end
  end

  def caveats
    <<~EOS
      Blaxel is a tool to ship AI agents that never slack.
    EOS
  end
end
