# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blaxel < Formula
  desc ""
  homepage "https://www.blaxel.ai"
  version "0.1.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/beamlit/toolkit/releases/download/v0.1.7/blaxel_Darwin_x86_64.tar.gz"
      sha256 "7658f8f3124c70f1bd95285f96924742ccee4092e4b3e382beb0bbeac4931a61"

      def install
        bin.install "blaxel"
        bin.install_symlink "blaxel" => "bl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/beamlit/toolkit/releases/download/v0.1.7/blaxel_Darwin_arm64.tar.gz"
      sha256 "2b4b7f4008042583527d318bb28fcb4ee1571a8a83d2e2164705709293d25706"

      def install
        bin.install "blaxel"
        bin.install_symlink "blaxel" => "bl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/beamlit/toolkit/releases/download/v0.1.7/blaxel_Linux_x86_64.tar.gz"
        sha256 "df735d395d321842e5f2b1ed19c0b9db5af8b198545ddb87e1397cd53ffd709e"

        def install
          bin.install "blaxel"
          bin.install_symlink "blaxel" => "bl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/beamlit/toolkit/releases/download/v0.1.7/blaxel_Linux_arm64.tar.gz"
        sha256 "f10f67fe100766de98c59232e4860fd369b7db0b1e764296fac31eb0413e059f"

        def install
          bin.install "blaxel"
          bin.install_symlink "blaxel" => "bl"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Blaxel is a tool to ship AI agents that never slack.
    EOS
  end
end
