# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blaxel < Formula
  desc ""
  homepage "https://www.blaxel.ai"
  version "0.1.85"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blaxel-ai/toolkit/releases/download/v0.1.85/blaxel_Darwin_x86_64.tar.gz"
      sha256 "5ed296a79b19c360db27cb421454b74320839231c8c0fbfc9ec4f81608ef6ca5"

      define_method(:install) do
        bin.install "blaxel"
        bin.install_symlink "blaxel" => "bl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blaxel-ai/toolkit/releases/download/v0.1.85/blaxel_Darwin_arm64.tar.gz"
      sha256 "ccea3c05a86e61e0d13264dea1f61bb4e369a5ab1867be90dffbf05d4aba6fed"

      define_method(:install) do
        bin.install "blaxel"
        bin.install_symlink "blaxel" => "bl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blaxel-ai/toolkit/releases/download/v0.1.85/blaxel_Linux_x86_64.tar.gz"
      sha256 "6c486dad9ae2f30db600d28856938025bd7c56cea0d19f8a6003c7cb905c163b"
      define_method(:install) do
        bin.install "blaxel"
        bin.install_symlink "blaxel" => "bl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blaxel-ai/toolkit/releases/download/v0.1.85/blaxel_Linux_arm64.tar.gz"
      sha256 "ff12dd4f113b32bd6552a2c1fab07b3a1153ed964b035f57e33693b76c3b7ce0"
      define_method(:install) do
        bin.install "blaxel"
        bin.install_symlink "blaxel" => "bl"
      end
    end
  end

  def caveats
    <<~EOS
      Blaxel is a tool to ship AI agents that never slack.
    EOS
  end
end
